import { defineType, defineField } from 'sanity';
import { buttonFields, iconField, section } from './shared';

export default defineType({
  name: 'settings',
  title: 'Site Settings',
  type: 'document',
  fieldsets: [
    section('general', 'General'),
    section('branding', 'Logo & Favicon'),
    section('contact', 'Contact Details', 'Used in the footer, the contact page, the menu and the call buttons.'),
    section('social', 'Social Media Links'),
    section('header', 'Header & Menu'),
    section('stickyBar', 'Phone Bottom Bar', 'The bar pinned to the bottom of the screen on phones.'),
    section('footer', 'Footer'),
    section('cookies', 'Cookie Banner'),
    section('notFound', '"Page Not Found" Page', 'Shown when a visitor opens a link that does not exist.'),
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Site Title',
      type: 'string',
      initialValue: 'Gerald Photo Video',
      fieldset: 'general',
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      description: 'Shown above the homepage heading when the Home Page has no tagline.',
      fieldset: 'general',
    }),
    defineField({
      name: 'description',
      title: 'Site Description',
      type: 'text',
      rows: 3,
      description: 'Used by search engines and when the site is shared.',
      fieldset: 'general',
    }),
    defineField({
      name: 'logo',
      title: 'Logo',
      type: 'image',
      description: 'Shown in the header, the footer and the homepage hero.',
      fieldset: 'branding',
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon',
      type: 'image',
      description: 'The small icon in the browser tab. A square image works best.',
      fieldset: 'branding',
    }),
    defineField({
      name: 'contactFormId',
      title: 'Contact Form ID',
      type: 'string',
      description: 'HoneyBook placement ID for the form on the contact page.',
      fieldset: 'contact',
    }),
    defineField({ name: 'phone', title: 'Phone Number', type: 'string', fieldset: 'contact' }),
    defineField({ name: 'email', title: 'Email Address', type: 'string', fieldset: 'contact' }),
    defineField({
      name: 'addressRegion',
      title: 'Service Area / Region',
      type: 'string',
      initialValue: 'Nebraska & Iowa',
      description: 'Displayed in the footer and contact page.',
      fieldset: 'contact',
    }),
    defineField({
      name: 'socialLinks',
      title: 'Social Media Links',
      type: 'object',
      fieldset: 'social',
      fields: [
        { name: 'facebook', type: 'url', title: 'Facebook URL' },
        { name: 'instagram', type: 'url', title: 'Instagram URL' },
        { name: 'tiktok', type: 'url', title: 'TikTok URL' },
        { name: 'youtube', type: 'url', title: 'YouTube URL' },
      ],
    }),
    defineField({
      name: 'navItems',
      title: 'Menu Links',
      type: 'array',
      description: 'The links in the header menu (desktop and phone), in order.',
      fieldset: 'header',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'label', type: 'string', title: 'Label' },
            { name: 'link', type: 'string', title: 'Link', description: 'A page on this site like /weddings, or a full URL.' },
          ],
          preview: { select: { title: 'label', subtitle: 'link' } },
        },
      ],
    }),
    ...buttonFields('headerButton', 'header', 'Header Button'),
    defineField({
      name: 'mobileCallLabel',
      title: 'Phone Menu "Call" Button Text',
      type: 'string',
      description: 'Shown before the phone number in the phone menu, e.g. "Call".',
      fieldset: 'header',
    }),
    iconField('stickyCallIcon', 'Call Button Icon', 'stickyBar'),
    defineField({ name: 'stickyCallLabel', title: 'Call Button Text', type: 'string', fieldset: 'stickyBar' }),
    iconField('stickyButtonIcon', 'Second Button Icon', 'stickyBar'),
    ...buttonFields('stickyButton', 'stickyBar', 'Second Button'),
    defineField({
      name: 'footerTagline',
      title: 'Footer Tagline',
      type: 'string',
      initialValue: "Timeless photography and cinematic films for life's most beautiful moments.",
      fieldset: 'footer',
    }),
    defineField({
      name: 'footerServingLabel',
      title: '"Serving" Heading Text',
      type: 'string',
      description: 'Shown before the service region, e.g. "Serving" → "Serving Nebraska & Iowa".',
      fieldset: 'footer',
    }),
    defineField({
      name: 'footerCities',
      title: 'City Links',
      type: 'array',
      description: 'The cities listed in the footer, in order.',
      fieldset: 'footer',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'label', type: 'string', title: 'City' },
            { name: 'link', type: 'string', title: 'Link', description: 'A page on this site like /omaha-wedding-photographer.' },
          ],
          preview: { select: { title: 'label', subtitle: 'link' } },
        },
      ],
    }),
    defineField({
      name: 'footerNote',
      title: 'Footer Note',
      type: 'string',
      initialValue: 'and surrounding areas.',
      description: 'Short text shown after the city links in the footer.',
      fieldset: 'footer',
    }),
    defineField({ name: 'footerConnectHeading', title: '"Connect" Heading', type: 'string', fieldset: 'footer' }),
    defineField({ name: 'footerContactHeading', title: '"Get In Touch" Heading', type: 'string', fieldset: 'footer' }),
    defineField({
      name: 'ctaPhoneLabel',
      title: '"Or call" Text',
      type: 'string',
      description: 'Shown before the phone number under the "Check Availability" band on most pages.',
      fieldset: 'footer',
    }),
    iconField('footerEmailIcon', 'Email Icon', 'footer'),
    iconField('footerPhoneIcon', 'Phone Icon', 'footer'),
    defineField({
      name: 'availabilityButtonLabel',
      title: 'Footer Button Label',
      type: 'string',
      initialValue: 'Check Availability',
      fieldset: 'footer',
    }),
    defineField({
      name: 'availabilityButtonLink',
      title: 'Footer Button Link',
      type: 'string',
      description: 'A page on this site like /contact, or a full URL.',
      fieldset: 'footer',
    }),
    defineField({
      name: 'copyrightLine',
      title: 'Copyright Line',
      type: 'string',
      description:
        'The whole bottom line. Write {year} for the current year and {name} for the Site Title, e.g. "© {year} {name}. All Rights Reserved."',
      fieldset: 'footer',
    }),
    defineField({
      name: 'copyrightText',
      title: 'Copyright Text (old)',
      type: 'string',
      description: 'Only used when Copyright Line above is empty. Shown after "© year Site Title.".',
      fieldset: 'footer',
      hidden: ({ document }) => Boolean(document?.copyrightLine),
    }),
    iconField('cookieIcon', 'Icon', 'cookies'),
    defineField({ name: 'cookieTitle', title: 'Title', type: 'string', fieldset: 'cookies' }),
    defineField({ name: 'cookieText', title: 'Text', type: 'text', rows: 4, fieldset: 'cookies' }),
    defineField({ name: 'cookieAcceptLabel', title: '"Accept" Button Text', type: 'string', fieldset: 'cookies' }),
    defineField({ name: 'cookieRejectLabel', title: '"Reject" Button Text', type: 'string', fieldset: 'cookies' }),
    ...buttonFields('cookiePolicy', 'cookies', 'Privacy Policy'),
    defineField({ name: 'notFoundHeading', title: 'Heading', type: 'string', fieldset: 'notFound' }),
    defineField({ name: 'notFoundText', title: 'Text', type: 'text', rows: 2, fieldset: 'notFound' }),
    ...buttonFields('notFoundButton', 'notFound'),
    ...buttonFields('notFoundSecondButton', 'notFound', 'Second Button'),
    defineField({
      name: 'notFoundLinksHeading',
      title: 'Links Heading',
      type: 'string',
      description: 'Above the list of links, which uses the menu links above.',
      fieldset: 'notFound',
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Site Settings' };
    },
  },
});
